project_id = "sfezwprbanvxsnwgvkhh"

[functions.create-test-user]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.extract-contract-data]
verify_jwt = false

[functions.enrich-lead]
verify_jwt = false

[functions.generate-email]
verify_jwt = false

[functions.fill-contract]
verify_jwt = false

[functions.generate-niche-emails]
verify_jwt = false

[functions.parse-pdf-contacts]
verify_jwt = false

[functions.send-niche-emails]
verify_jwt = false

[functions.generate-notifications]
verify_jwt = false
